insert into provincias(codigo,nombre,idregion) values('0101','Chachapoyas',1);
insert into provincias(codigo,nombre,idregion) values('0102','Bagua',1);
insert into provincias(codigo,nombre,idregion) values('0103','Bongará',1);
insert into provincias(codigo,nombre,idregion) values('0104','Condorcanqui',1);
insert into provincias(codigo,nombre,idregion) values('0105','Luya',1);
insert into provincias(codigo,nombre,idregion) values('0106','Rodríguez de Mendoza',1);
insert into provincias(codigo,nombre,idregion) values('0107','Utcubamba',1);
insert into provincias(codigo,nombre,idregion) values('0201','Huaraz',2);
insert into provincias(codigo,nombre,idregion) values('0202','Aija',2);
insert into provincias(codigo,nombre,idregion) values('0203','Antonio Raymondi',2);
insert into provincias(codigo,nombre,idregion) values('0204','Asunción',2);
insert into provincias(codigo,nombre,idregion) values('0205','Bolognesi',2);
insert into provincias(codigo,nombre,idregion) values('0206','Carhuaz',2);
insert into provincias(codigo,nombre,idregion) values('0207','Carlos Fermín Fitzcarrald',2);
insert into provincias(codigo,nombre,idregion) values('0208','Casma',2);
insert into provincias(codigo,nombre,idregion) values('0209','Corongo',2);
insert into provincias(codigo,nombre,idregion) values('0210','Huari',2);
insert into provincias(codigo,nombre,idregion) values('0211','Huarmey',2);
insert into provincias(codigo,nombre,idregion) values('0212','Huaylas',2);
insert into provincias(codigo,nombre,idregion) values('0213','Mariscal Luzuriaga',2);
insert into provincias(codigo,nombre,idregion) values('0214','Ocros',2);
insert into provincias(codigo,nombre,idregion) values('0215','Pallasca',2);
insert into provincias(codigo,nombre,idregion) values('0216','Pomabamba',2);
insert into provincias(codigo,nombre,idregion) values('0217','Recuay',2);
insert into provincias(codigo,nombre,idregion) values('0218','Santa',2);
insert into provincias(codigo,nombre,idregion) values('0219','Sihuas',2);
insert into provincias(codigo,nombre,idregion) values('0220','Yungay',2);
insert into provincias(codigo,nombre,idregion) values('0301','Abancay',3);
insert into provincias(codigo,nombre,idregion) values('0302','Andahuaylas',3);
insert into provincias(codigo,nombre,idregion) values('0303','Antabamba',3);
insert into provincias(codigo,nombre,idregion) values('0304','Aymaraes',3);
insert into provincias(codigo,nombre,idregion) values('0305','Cotabambas',3);
insert into provincias(codigo,nombre,idregion) values('0306','Chincheros',3);
insert into provincias(codigo,nombre,idregion) values('0307','Grau',3);
insert into provincias(codigo,nombre,idregion) values('0401','Arequipa',4);
insert into provincias(codigo,nombre,idregion) values('0402','Camaná',4);
insert into provincias(codigo,nombre,idregion) values('0403','Caravelí',4);
insert into provincias(codigo,nombre,idregion) values('0404','Castilla',4);
insert into provincias(codigo,nombre,idregion) values('0405','Caylloma',4);
insert into provincias(codigo,nombre,idregion) values('0406','Condesuyos',4);
insert into provincias(codigo,nombre,idregion) values('0407','Islay',4);
insert into provincias(codigo,nombre,idregion) values('0408','La Uniòn',4);
insert into provincias(codigo,nombre,idregion) values('0501','Huamanga',5);
insert into provincias(codigo,nombre,idregion) values('0502','Cangallo',5);
insert into provincias(codigo,nombre,idregion) values('0503','Huanca Sancos',5);
insert into provincias(codigo,nombre,idregion) values('0504','Huanta',5);
insert into provincias(codigo,nombre,idregion) values('0505','La Mar',5);
insert into provincias(codigo,nombre,idregion) values('0506','Lucanas',5);
insert into provincias(codigo,nombre,idregion) values('0507','Parinacochas',5);
insert into provincias(codigo,nombre,idregion) values('0508','Pàucar del Sara Sara',5);
insert into provincias(codigo,nombre,idregion) values('0509','Sucre',5);
insert into provincias(codigo,nombre,idregion) values('0510','Víctor Fajardo',5);
insert into provincias(codigo,nombre,idregion) values('0511','Vilcas Huamán',5);
insert into provincias(codigo,nombre,idregion) values('0601','Cajamarca',6);
insert into provincias(codigo,nombre,idregion) values('0602','Cajabamba',6);
insert into provincias(codigo,nombre,idregion) values('0603','Celendín',6);
insert into provincias(codigo,nombre,idregion) values('0604','Chota',6);
insert into provincias(codigo,nombre,idregion) values('0605','Contumazá',6);
insert into provincias(codigo,nombre,idregion) values('0606','Cutervo',6);
insert into provincias(codigo,nombre,idregion) values('0607','Hualgayoc',6);
insert into provincias(codigo,nombre,idregion) values('0608','Jaén',6);
insert into provincias(codigo,nombre,idregion) values('0609','San Ignacio',6);
insert into provincias(codigo,nombre,idregion) values('0610','San Marcos',6);
insert into provincias(codigo,nombre,idregion) values('0611','San Miguel',6);
insert into provincias(codigo,nombre,idregion) values('0612','San Pablo',6);
insert into provincias(codigo,nombre,idregion) values('0613','Santa Cruz',6);
insert into provincias(codigo,nombre,idregion) values('0701','Prov. Const. del Callao',7);
insert into provincias(codigo,nombre,idregion) values('0801','Cusco',8);
insert into provincias(codigo,nombre,idregion) values('0802','Acomayo',8);
insert into provincias(codigo,nombre,idregion) values('0803','Anta',8);
insert into provincias(codigo,nombre,idregion) values('0804','Calca',8);
insert into provincias(codigo,nombre,idregion) values('0805','Canas',8);
insert into provincias(codigo,nombre,idregion) values('0806','Canchis',8);
insert into provincias(codigo,nombre,idregion) values('0807','Chumbivilcas',8);
insert into provincias(codigo,nombre,idregion) values('0808','Espinar',8);
insert into provincias(codigo,nombre,idregion) values('0809','La Convención',8);
insert into provincias(codigo,nombre,idregion) values('0810','Paruro',8);
insert into provincias(codigo,nombre,idregion) values('0811','Paucartambo',8);
insert into provincias(codigo,nombre,idregion) values('0812','Quispicanchi',8);
insert into provincias(codigo,nombre,idregion) values('0813','Urubamba',8);
insert into provincias(codigo,nombre,idregion) values('0901','Huancavelica',9);
insert into provincias(codigo,nombre,idregion) values('0902','Acobamba',9);
insert into provincias(codigo,nombre,idregion) values('0903','Angaraes',9);
insert into provincias(codigo,nombre,idregion) values('0904','Castrovirreyna',9);
insert into provincias(codigo,nombre,idregion) values('0905','Churcampa',9);
insert into provincias(codigo,nombre,idregion) values('0906','Huaytará',9);
insert into provincias(codigo,nombre,idregion) values('0907','Tayacaja',9);
insert into provincias(codigo,nombre,idregion) values('1001','Huánuco',10);
insert into provincias(codigo,nombre,idregion) values('1002','Ambo',10);
insert into provincias(codigo,nombre,idregion) values('1003','Dos de Mayo',10);
insert into provincias(codigo,nombre,idregion) values('1004','Huacaybamba',10);
insert into provincias(codigo,nombre,idregion) values('1005','Huamalíes',10);
insert into provincias(codigo,nombre,idregion) values('1006','Leoncio Prado',10);
insert into provincias(codigo,nombre,idregion) values('1007','Marañón',10);
insert into provincias(codigo,nombre,idregion) values('1008','Pachitea',10);
insert into provincias(codigo,nombre,idregion) values('1009','Puerto Inca',10);
insert into provincias(codigo,nombre,idregion) values('1010','Lauricocha ',10);
insert into provincias(codigo,nombre,idregion) values('1011','Yarowilca ',10);
insert into provincias(codigo,nombre,idregion) values('1101','Ica ',11);
insert into provincias(codigo,nombre,idregion) values('1102','Chincha ',11);
insert into provincias(codigo,nombre,idregion) values('1103','Nasca ',11);
insert into provincias(codigo,nombre,idregion) values('1104','Palpa ',11);
insert into provincias(codigo,nombre,idregion) values('1105','Pisco ',11);
insert into provincias(codigo,nombre,idregion) values('1201','Huancayo ',12);
insert into provincias(codigo,nombre,idregion) values('1202','Concepción ',12);
insert into provincias(codigo,nombre,idregion) values('1203','Chanchamayo ',12);
insert into provincias(codigo,nombre,idregion) values('1204','Jauja ',12);
insert into provincias(codigo,nombre,idregion) values('1205','Junín ',12);
insert into provincias(codigo,nombre,idregion) values('1206','Satipo ',12);
insert into provincias(codigo,nombre,idregion) values('1207','Tarma ',12);
insert into provincias(codigo,nombre,idregion) values('1208','Yauli ',12);
insert into provincias(codigo,nombre,idregion) values('1209','Chupaca ',12);
insert into provincias(codigo,nombre,idregion) values('1301','Trujillo ',13);
insert into provincias(codigo,nombre,idregion) values('1302','Ascope ',13);
insert into provincias(codigo,nombre,idregion) values('1303','Bolívar ',13);
insert into provincias(codigo,nombre,idregion) values('1304','Chepén ',13);
insert into provincias(codigo,nombre,idregion) values('1305','Julcán ',13);
insert into provincias(codigo,nombre,idregion) values('1306','Otuzco ',13);
insert into provincias(codigo,nombre,idregion) values('1307','Pacasmayo ',13);
insert into provincias(codigo,nombre,idregion) values('1308','Pataz ',13);
insert into provincias(codigo,nombre,idregion) values('1309','Sánchez Carrión ',13);
insert into provincias(codigo,nombre,idregion) values('1310','Santiago de Chuco ',13);
insert into provincias(codigo,nombre,idregion) values('1311','Gran Chimú ',13);
insert into provincias(codigo,nombre,idregion) values('1312','Virú ',13);
insert into provincias(codigo,nombre,idregion) values('1401','Chiclayo ',14);
insert into provincias(codigo,nombre,idregion) values('1402','Ferreñafe ',14);
insert into provincias(codigo,nombre,idregion) values('1403','Lambayeque ',14);
insert into provincias(codigo,nombre,idregion) values('1501','Lima ',15);
insert into provincias(codigo,nombre,idregion) values('1502','Barranca ',15);
insert into provincias(codigo,nombre,idregion) values('1503','Cajatambo ',15);
insert into provincias(codigo,nombre,idregion) values('1504','Canta ',15);
insert into provincias(codigo,nombre,idregion) values('1505','Cañete ',15);
insert into provincias(codigo,nombre,idregion) values('1506','Huaral ',15);
insert into provincias(codigo,nombre,idregion) values('1507','Huarochirí ',15);
insert into provincias(codigo,nombre,idregion) values('1508','Huaura ',15);
insert into provincias(codigo,nombre,idregion) values('1509','Oyón ',15);
insert into provincias(codigo,nombre,idregion) values('1510','Yauyos ',15);
insert into provincias(codigo,nombre,idregion) values('1601','Maynas ',16);
insert into provincias(codigo,nombre,idregion) values('1602','Alto Amazonas ',16);
insert into provincias(codigo,nombre,idregion) values('1603','Loreto ',16);
insert into provincias(codigo,nombre,idregion) values('1604','Mariscal Ramón Castilla ',16);
insert into provincias(codigo,nombre,idregion) values('1605','Requena ',16);
insert into provincias(codigo,nombre,idregion) values('1606','Ucayali ',16);
insert into provincias(codigo,nombre,idregion) values('1607','Datem del Marañón ',16);
insert into provincias(codigo,nombre,idregion) values('1608','Putumayo',16);
insert into provincias(codigo,nombre,idregion) values('1701','Tambopata ',17);
insert into provincias(codigo,nombre,idregion) values('1702','Manu ',17);
insert into provincias(codigo,nombre,idregion) values('1703','Tahuamanu ',17);
insert into provincias(codigo,nombre,idregion) values('1801','Mariscal Nieto ',18);
insert into provincias(codigo,nombre,idregion) values('1802','General Sánchez Cerro ',18);
insert into provincias(codigo,nombre,idregion) values('1803','Ilo ',18);
insert into provincias(codigo,nombre,idregion) values('1901','Pasco ',19);
insert into provincias(codigo,nombre,idregion) values('1902','Daniel Alcides Carrión ',19);
insert into provincias(codigo,nombre,idregion) values('1903','Oxapampa ',19);
insert into provincias(codigo,nombre,idregion) values('2001','Piura ',20);
insert into provincias(codigo,nombre,idregion) values('2002','Ayabaca ',20);
insert into provincias(codigo,nombre,idregion) values('2003','Huancabamba ',20);
insert into provincias(codigo,nombre,idregion) values('2004','Morropón ',20);
insert into provincias(codigo,nombre,idregion) values('2005','Paita ',20);
insert into provincias(codigo,nombre,idregion) values('2006','Sullana ',20);
insert into provincias(codigo,nombre,idregion) values('2007','Talara ',20);
insert into provincias(codigo,nombre,idregion) values('2008','Sechura ',20);
insert into provincias(codigo,nombre,idregion) values('2101','Puno ',21);
insert into provincias(codigo,nombre,idregion) values('2102','Azángaro ',21);
insert into provincias(codigo,nombre,idregion) values('2103','Carabaya ',21);
insert into provincias(codigo,nombre,idregion) values('2104','Chucuito ',21);
insert into provincias(codigo,nombre,idregion) values('2105','El Collao ',21);
insert into provincias(codigo,nombre,idregion) values('2106','Huancané ',21);
insert into provincias(codigo,nombre,idregion) values('2107','Lampa ',21);
insert into provincias(codigo,nombre,idregion) values('2108','Melgar ',21);
insert into provincias(codigo,nombre,idregion) values('2109','Moho ',21);
insert into provincias(codigo,nombre,idregion) values('2110','San Antonio de Putina ',21);
insert into provincias(codigo,nombre,idregion) values('2111','San Román ',21);
insert into provincias(codigo,nombre,idregion) values('2112','Sandia ',21);
insert into provincias(codigo,nombre,idregion) values('2113','Yunguyo ',21);
insert into provincias(codigo,nombre,idregion) values('2201','Moyobamba ',22);
insert into provincias(codigo,nombre,idregion) values('2202','Bellavista ',22);
insert into provincias(codigo,nombre,idregion) values('2203','El Dorado ',22);
insert into provincias(codigo,nombre,idregion) values('2204','Huallaga ',22);
insert into provincias(codigo,nombre,idregion) values('2205','Lamas ',22);
insert into provincias(codigo,nombre,idregion) values('2206','Mariscal Cáceres ',22);
insert into provincias(codigo,nombre,idregion) values('2207','Picota ',22);
insert into provincias(codigo,nombre,idregion) values('2208','Rioja ',22);
insert into provincias(codigo,nombre,idregion) values('2209','San Martín ',22);
insert into provincias(codigo,nombre,idregion) values('2210','Tocache ',22);
insert into provincias(codigo,nombre,idregion) values('2301','Tacna ',23);
insert into provincias(codigo,nombre,idregion) values('2302','Candarave ',23);
insert into provincias(codigo,nombre,idregion) values('2303','Jorge Basadre ',23);
insert into provincias(codigo,nombre,idregion) values('2304','Tarata ',23);
insert into provincias(codigo,nombre,idregion) values('2401','Tumbes ',24);
insert into provincias(codigo,nombre,idregion) values('2402','Contralmirante Villar ',24);
insert into provincias(codigo,nombre,idregion) values('2403','Zarumilla ',24);
insert into provincias(codigo,nombre,idregion) values('2501','Coronel Portillo ',25);
insert into provincias(codigo,nombre,idregion) values('2502','Atalaya ',25);
insert into provincias(codigo,nombre,idregion) values('2503','Padre Abad ',25);
insert into provincias(codigo,nombre,idregion) values('2504','Purús',25);
