insert into region(codigo,nombre) values('01','Amazonas');
insert into region(codigo,nombre) values('02','Áncash');
insert into region(codigo,nombre) values('03','Apurímac');
insert into region(codigo,nombre) values('04','Arequipa');
insert into region(codigo,nombre) values('05','Ayacucho');
insert into region(codigo,nombre) values('06','Cajamarca');
insert into region(codigo,nombre) values('07','Callao');
insert into region(codigo,nombre) values('08','Cusco');
insert into region(codigo,nombre) values('09','Huancavelica');
insert into region(codigo,nombre) values('10','Huánuco');
insert into region(codigo,nombre) values('11','Ica');
insert into region(codigo,nombre) values('12','Junín');
insert into region(codigo,nombre) values('13','La Libertad');
insert into region(codigo,nombre) values('14','Lambayeque');
insert into region(codigo,nombre) values('15','Lima');
insert into region(codigo,nombre) values('16','Loreto');
insert into region(codigo,nombre) values('17','Madre de Dios');
insert into region(codigo,nombre) values('18','Moquegua');
insert into region(codigo,nombre) values('19','Pasco');
insert into region(codigo,nombre) values('20','Piura');
insert into region(codigo,nombre) values('21','Puno');
insert into region(codigo,nombre) values('22','San Martín');
insert into region(codigo,nombre) values('23','Tacna');
insert into region(codigo,nombre) values('24','Tumbes');
insert into region(codigo,nombre) values('25','Ucayali');
